# This workflow will build and run a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Setup Swift
      uses: SwiftyLab/setup-swift@latest
    - name: Run
      run: swift run
    - name: Build
      run: swift build -v
